"""
StartupPilot AI — Research Platform Data Models

Pydantic definitions for the Agentic Research Planner and Multi-Hop Navigation system.
"""

from __future__ import annotations

import hashlib
from datetime import datetime, timezone
from typing import Any, Optional
from pydantic import BaseModel, Field


class ResearchSubQuestion(BaseModel):
    """A decomposed sub-question generated by the Research Planner."""
    question_id: str
    text: str
    target_pages: list[str] = Field(
        default_factory=list,
        description="Page IDs initially targeted for exploration"
    )
    status: str = Field(
        default="pending",
        description="Status of this sub-question: pending|completed"
    )


class ResearchPlan(BaseModel):
    """The master research plan constructed before agent execution."""
    project_id: str
    startup_idea: str
    agent_type: str
    sub_questions: list[ResearchSubQuestion] = Field(default_factory=list)
    created_at: datetime = Field(
        default_factory=lambda: datetime.now(timezone.utc)
    )


class EvidenceItem(BaseModel):
    """A specific factual claim or evidence snippet gathered during navigation."""
    evidence_id: str
    page_id: str
    title_or_name: str
    fact: str
    relevance_reasoning: str
    timestamp: datetime = Field(
        default_factory=lambda: datetime.now(timezone.utc)
    )


class ResearchTrace(BaseModel):
    """A chronological record of the multi-hop research traversal process."""
    project_id: str
    agent_type: str
    navigation_path: list[str] = Field(
        default_factory=list,
        description="Ordered list of page IDs visited"
    )
    evidence_gathered: list[EvidenceItem] = Field(default_factory=list)
    reasoning_chain: list[str] = Field(
        default_factory=list,
        description="Reasoning logs explaining the logic behind each hop"
    )
    depth: int = Field(default=0, description="Maximum navigation depth achieved")
    metrics: dict[str, Any] = Field(
        default_factory=dict,
        description="Summary statistics (pages_explored, evidence_count, etc.)"
    )


class ResearchMemory(BaseModel):
    """Caches successful navigation paths to optimize future research operations."""
    project_id: str
    successful_paths: dict[str, list[str]] = Field(
        default_factory=dict,
        description="agent_type/query -> successful list of page_ids"
    )
    updated_at: datetime = Field(
        default_factory=lambda: datetime.now(timezone.utc)
    )

    def learn_path(self, key: str, path: list[str]) -> None:
        """Record a successful path for a task key."""
        # Evict oldest path if size limit (100) exceeded
        if len(self.successful_paths) >= 100 and key not in self.successful_paths:
            oldest_key = next(iter(self.successful_paths))
            self.successful_paths.pop(oldest_key, None)
        self.successful_paths[key] = path
        self.updated_at = datetime.now(timezone.utc)

    def get_path(self, key: str) -> Optional[list[str]]:
        """Retrieve a cached path for a task key."""
        return self.successful_paths.get(key)
