"""
StartupPilot AI — Report Generator

Generates comprehensive startup analysis reports in three formats:
- Markdown (.md) — clean, readable, version-control friendly
- HTML (.html) — styled with professional CSS, embeddable diagrams
- PDF (.pdf) — downloadable, shareable

Uses Jinja2 for HTML templating and fpdf2 for PDF generation.
"""

from __future__ import annotations

import logging
import re
import time
from pathlib import Path
from typing import Any, Optional

import markdown as md

from config import get_settings, REPORTS_DIR

logger = logging.getLogger(__name__)


def generate_report(state: dict[str, Any]) -> str:
    """Generate a Markdown report from the analysis state.

    Compiles all agent outputs into a structured, professional report.

    Args:
        state: The complete StartupAnalysisState after workflow completion.

    Returns:
        The report content as a Markdown string.
    """
    startup_idea = state.get("startup_idea", "Unknown Startup")
    project_id = state.get("project_id", "unknown")
    timestamp = time.strftime("%B %d, %Y", time.localtime())

    sections = [
        _title_section(startup_idea, timestamp),
        _executive_summary(state),
        _industry_analysis(state),
        _market_analysis(state),
        _competitor_analysis(state),
        _swot_analysis(state),
        _business_strategy(state),
        _agent_discussion(state),
        _architecture_design(state),
        _cost_analysis(state),
        _final_recommendations(state),
        _appendix(state),
    ]

    report = "\n\n---\n\n".join(sections)

    # Save report files
    _save_report(project_id, report)

    logger.info("Generated report for project %s (%d chars)", project_id, len(report))
    return report


def save_report_as_html(project_id: str, markdown_content: str) -> str:
    """Convert Markdown report to styled HTML.

    Returns the file path of the saved HTML report.
    """
    html_body = md.markdown(
        markdown_content,
        extensions=["tables", "fenced_code", "toc"],
    )

    html = f"""<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>StartupPilot AI Report — {project_id}</title>
    <style>
        * {{ margin: 0; padding: 0; box-sizing: border-box; }}
        body {{
            font-family: 'Segoe UI', Tahoma, Geneva, Verdana, sans-serif;
            line-height: 1.7;
            color: #e0e0e0;
            background: #121212;
            max-width: 900px;
            margin: 0 auto;
            padding: 40px 20px;
        }}
        h1 {{ color: #bb86fc; font-size: 2.2em; margin: 30px 0 15px; border-bottom: 2px solid #333; padding-bottom: 10px; }}
        h2 {{ color: #03dac6; font-size: 1.6em; margin: 25px 0 12px; }}
        h3 {{ color: #cf6679; font-size: 1.3em; margin: 20px 0 10px; }}
        p {{ margin: 10px 0; }}
        ul, ol {{ margin: 10px 0 10px 25px; }}
        li {{ margin: 5px 0; }}
        table {{ border-collapse: collapse; width: 100%; margin: 15px 0; }}
        th, td {{ border: 1px solid #333; padding: 10px 14px; text-align: left; }}
        th {{ background: #1e1e1e; color: #bb86fc; font-weight: 600; }}
        tr:nth-child(even) {{ background: #1a1a1a; }}
        code {{ background: #1e1e1e; padding: 2px 6px; border-radius: 3px; font-size: 0.9em; color: #03dac6; }}
        pre {{ background: #1e1e1e; padding: 16px; border-radius: 8px; overflow-x: auto; margin: 15px 0; }}
        pre code {{ background: none; padding: 0; }}
        blockquote {{ border-left: 4px solid #bb86fc; padding: 10px 20px; margin: 15px 0; background: #1a1a1a; border-radius: 0 8px 8px 0; }}
        hr {{ border: none; border-top: 1px solid #333; margin: 30px 0; }}
        strong {{ color: #fff; }}
        a {{ color: #bb86fc; text-decoration: none; }}
        a:hover {{ text-decoration: underline; }}
        .header {{ text-align: center; padding: 40px 0; border-bottom: 2px solid #333; margin-bottom: 30px; }}
        .header h1 {{ border: none; }}
        .footer {{ text-align: center; padding: 30px 0; margin-top: 40px; border-top: 1px solid #333; color: #666; font-size: 0.9em; }}
    </style>
</head>
<body>
    <div class="header">
        <h1>🚀 StartupPilot AI</h1>
        <p>Multi-Agent Startup Intelligence Report</p>
    </div>
    {html_body}
    <div class="footer">
        <p>Generated by StartupPilot AI — Multi-Agent Startup Intelligence Platform</p>
        <p>Powered by LangGraph • CrewAI • AutoGen • LangChain</p>
    </div>
</body>
</html>"""

    reports_dir = Path(get_settings().reports_dir)
    reports_dir.mkdir(parents=True, exist_ok=True)
    file_path = reports_dir / f"{project_id}.html"
    file_path.write_text(html, encoding="utf-8")

    logger.info("Saved HTML report: %s", file_path)
    return str(file_path)


def save_report_as_pdf(project_id: str, markdown_content: str) -> str:
    """Convert Markdown report to PDF.

    Uses fpdf2 for pure-Python PDF generation (no system dependencies).
    Returns the file path of the saved PDF.
    """
    try:
        from fpdf import FPDF

        pdf = FPDF()
        pdf.set_auto_page_break(auto=True, margin=15)
        pdf.add_page()

        # Title
        pdf.set_font("Helvetica", "B", 20)
        pdf.cell(0, 15, "StartupPilot AI Report", ln=True, align="C")
        pdf.set_font("Helvetica", "", 10)
        pdf.cell(0, 8, f"Project: {project_id}", ln=True, align="C")
        pdf.ln(10)

        # Content — process Markdown line by line
        lines = markdown_content.split("\n")
        for line in lines:
            line = line.strip()

            if line.startswith("# "):
                pdf.ln(5)
                pdf.set_font("Helvetica", "B", 16)
                pdf.multi_cell(0, 8, _clean_text(line[2:]))
                pdf.ln(3)
            elif line.startswith("## "):
                pdf.ln(4)
                pdf.set_font("Helvetica", "B", 14)
                pdf.multi_cell(0, 7, _clean_text(line[3:]))
                pdf.ln(2)
            elif line.startswith("### "):
                pdf.ln(3)
                pdf.set_font("Helvetica", "B", 12)
                pdf.multi_cell(0, 6, _clean_text(line[4:]))
                pdf.ln(2)
            elif line.startswith("- ") or line.startswith("* "):
                pdf.set_font("Helvetica", "", 10)
                pdf.multi_cell(0, 5, f"  • {_clean_text(line[2:])}")
            elif line.startswith("---"):
                pdf.ln(5)
                pdf.line(10, pdf.get_y(), 200, pdf.get_y())
                pdf.ln(5)
            elif line:
                pdf.set_font("Helvetica", "", 10)
                pdf.multi_cell(0, 5, _clean_text(line))
            else:
                pdf.ln(3)

        reports_dir = Path(get_settings().reports_dir)
        reports_dir.mkdir(parents=True, exist_ok=True)
        file_path = reports_dir / f"{project_id}.pdf"
        pdf.output(str(file_path))

        logger.info("Saved PDF report: %s", file_path)
        return str(file_path)

    except Exception as e:
        logger.error("PDF generation failed: %s", e)
        return ""


# ══════════════════════════════════════════════════════════════════════════════
# Report Sections
# ══════════════════════════════════════════════════════════════════════════════


def _title_section(startup_idea: str, timestamp: str) -> str:
    return (
        f"# 🚀 StartupPilot AI — Startup Analysis Report\n\n"
        f"**Startup Idea:** {startup_idea}\n\n"
        f"**Generated:** {timestamp}\n\n"
        f"**Platform:** StartupPilot AI — Multi-Agent Startup Intelligence Platform\n\n"
        f"**Powered by:** LangGraph • CrewAI • AutoGen • LangChain • ChromaDB"
    )


def _executive_summary(state: dict[str, Any]) -> str:
    research = state.get("research", "")
    strategy = state.get("business_strategy", "")
    # Extract first 300 chars as summary if no dedicated summary
    summary = research[:300] if research else "Analysis pending."
    return f"## 📋 Executive Summary\n\n{summary}"


def _industry_analysis(state: dict[str, Any]) -> str:
    return f"## 🔬 Industry Analysis\n\n{state.get('research', 'No research data available.')}"


def _market_analysis(state: dict[str, Any]) -> str:
    return f"## 📊 Market Analysis\n\n{state.get('market_analysis', 'No market data available.')}"


def _competitor_analysis(state: dict[str, Any]) -> str:
    return f"## 🎯 Competitor Analysis\n\n{state.get('competitors', 'No competitor data available.')}"


def _swot_analysis(state: dict[str, Any]) -> str:
    return f"## ⚡ SWOT Analysis\n\n{state.get('swot', 'No SWOT data available.')}"


def _business_strategy(state: dict[str, Any]) -> str:
    return f"## 💡 Business Strategy & Recommendations\n\n{state.get('business_strategy', 'No strategy data available.')}"


def _agent_discussion(state: dict[str, Any]) -> str:
    return f"## 💬 Agent Discussion Summary\n\n{state.get('discussion_transcript', 'No discussion data available.')}"


def _architecture_design(state: dict[str, Any]) -> str:
    return f"## 🏗️ Cloud Architecture Design\n\n{state.get('architecture', 'No architecture data available.')}"


def _cost_analysis(state: dict[str, Any]) -> str:
    return f"## 💰 Infrastructure Cost Analysis\n\n{state.get('cost_estimates', 'No cost data available.')}"


def _final_recommendations(state: dict[str, Any]) -> str:
    metrics = state.get("execution_metrics", {})
    routing = state.get("llm_routing_log", [])

    rec = "## 🎯 Final Recommendations\n\n"
    rec += "Based on the comprehensive analysis by 8 specialized AI agents and "
    rec += "a multi-agent discussion, here are the key recommendations:\n\n"
    rec += "1. **Start with an MVP** focused on core value proposition\n"
    rec += "2. **Validate with early customers** before scaling\n"
    rec += "3. **Use cloud-native architecture** for cost efficiency\n"
    rec += "4. **Build iteratively** based on market feedback\n"

    return rec


def _appendix(state: dict[str, Any]) -> str:
    metrics = state.get("execution_metrics", {})
    routing = state.get("llm_routing_log", [])

    appendix = "## 📎 Appendix: Analysis Metadata\n\n"
    appendix += "### Agent Execution Metrics\n\n"
    appendix += "| Agent | Time (ms) | Model Used |\n|---|---|---|\n"

    for agent, data in metrics.items():
        if isinstance(data, dict):
            time_ms = data.get("time_ms", data.get("execution_time_ms", "N/A"))
            model = data.get("model_used", data.get("model", "N/A"))
            appendix += f"| {agent} | {time_ms} | {model} |\n"

    if routing:
        appendix += "\n### LLM Routing Decisions\n\n"
        appendix += "| Task | Provider | Model |\n|---|---|---|\n"
        for r in routing:
            appendix += f"| {r.get('task', 'N/A')} | {r.get('provider', 'N/A')} | {r.get('model', 'N/A')} |\n"

    return appendix


# ══════════════════════════════════════════════════════════════════════════════
# Helpers
# ══════════════════════════════════════════════════════════════════════════════


def _save_report(project_id: str, report: str) -> None:
    """Save report as Markdown file."""
    reports_dir = Path(get_settings().reports_dir)
    reports_dir.mkdir(parents=True, exist_ok=True)
    file_path = reports_dir / f"{project_id}.md"
    file_path.write_text(report, encoding="utf-8")
    logger.info("Saved MD report: %s", file_path)


def _clean_text(text: str) -> str:
    """Clean Markdown formatting for PDF output."""
    text = re.sub(r"\*\*(.*?)\*\*", r"\1", text)  # Bold
    text = re.sub(r"\*(.*?)\*", r"\1", text)  # Italic
    text = re.sub(r"`(.*?)`", r"\1", text)  # Code
    text = text.encode("latin-1", errors="replace").decode("latin-1")
    return text
